class Places  {
  final String assets;
  final String name;
  final String location;
  final String about;
  final double rating;
  final int bathroom;
  final int bedroom;
  final int area;
  final int price;
  final String tag;

  Places({
    required this.assets, 
    required this.name, 
    required this.location, 
    required this.about, 
    required this.rating,
     required this.bathroom, 
    required this.bedroom, 
    required this.area, 
    required this.price, 
    required this.tag
    });

}

final buildings = [
      Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident ', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 2, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jfekj.webp', 
        name: 'The Resident', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 1, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jfekj.webp', 
        name: 'The Resident', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 3, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jfekj.webp', 
        name: 'The Resident', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 5, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 3, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: '', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'NEW YORK', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: '', 
        location: '', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: '', 
        location: '', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: '', 
        location: '', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: '', 
        location: '', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),

      
    ];
       final popular = [
         Places(
        assets: 'android/assets/images/jfekj.webp', 
        name: 'The Resident', 
        location: 'TOKYO', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 5, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'JAPAN', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 2, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jfekj.webp', 
        name: 'The Resident', 
        location: 'CHINA', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 3, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'Nsam', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'NEW YORK', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 5, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jfekj.webp', 
        name: 'The Resident', 
        location: 'Amity', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 1, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'bertoua', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jfekj.webp', 
        name: 'The Resident', 
        location: 'ICT university', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'Daker', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'Damas', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: 'The Resident', 
        location: 'Behind Millionair Hotel', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: '', 
        location: '', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: '', 
        location: '', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: '', 
        location: '', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: '', 
        location: '', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: '', 
        location: '', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: '', 
        location: '', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),    Places(
        assets: 'android/assets/images/jjfbs.webp', 
        name: '', 
        location: '', 
        about: 'This property is managed by Mr david and Has beign well maintained overtime', 
        rating: 4, 
        bathroom: 3, 
        bedroom: 4, 
        area: 1000, 
        price: 500, 
        tag: 'Family, luxury',
      ),
       ];